
[functions.brevo-add-contact]
enabled = true
verify_jwt = false
import_map = "./functions/brevo-add-contact/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/brevo-add-contact/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/brevo-add-contact/*.html" ]

[functions.send-welcome-email]
enabled = true
verify_jwt = false
import_map = "./functions/send-welcome-email/deno.json"
entrypoint = "./functions/send-welcome-email/index.ts"

[functions.subscription-emails]
enabled = true
verify_jwt = false
entrypoint = "./functions/subscription-emails/index.ts"

[functions.payment-webhook]
enabled = true
verify_jwt = false
entrypoint = "./functions/payment-webhook/index.ts"

